[Lab 1]Added website markup
kasaty/effective-lab-works pull request #1
Opened 2022-11-03 22:17 UTC by kasaty

Дутов Константин

2022-11-04 19:04 UTC, konstantinzelinsky commented
Вот эта часть в адаптивной верстке требует доработки.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/57330800/200055226-5dd98f9d-20d1-42fe-bb25-b5231f5e96d9.png">

Без доработки готов поставить 12 баллов

2022-11-04 19:04 UTC, konstantinzelinsky requested changes
Адаптив требует доработки

2022-11-04 19:48 UTC, kasaty commented
Добрый день.
Если дело в отступе? То был залита не та версия работы ( Если нужно могу перезалить ) скрин 1. 
![image](https://user-images.githubusercontent.com/77506942/200061718-99c99043-7319-4cad-973c-c75a73e9eba3.png)
Если дело в тексте, то в задании было указано, что в фигме просто пример и можно реализовать макет на свой взгляд.
( Скрин 2 )
![image](https://user-images.githubusercontent.com/77506942/200062020-4623b7c7-1026-4f57-9a8a-8b456038204e.png)
Возможно будет получить 14 баллов если ошибка была с моей стороны ( Залит не тот проект ) ?
Заранее спасибо за ответ.)

2022-11-05 07:37 UTC, konstantinzelinsky commented
Да, залей, пожалуйста, финальную версию

2022-11-07 17:31 UTC, konstantinzelinsky commented
Есть некоторые недоработки все равно
Здесь не хватает картинки с желтыми точками и расположена она в макете по-другому
<img width="549" alt="image" src="https://user-images.githubusercontent.com/57330800/200375726-6befd802-e48d-4580-aa78-f426f702b894.png">

Картинка с линиями расположена в макете по-другому
<img width="495" alt="image" src="https://user-images.githubusercontent.com/57330800/200375989-15d828b3-5694-48a4-a00a-63e133d558e7.png">

В мобильной верстке желтая картинка с бэкграунда пропадает
<img width="299" alt="image" src="https://user-images.githubusercontent.com/57330800/200376158-26d4803b-e5eb-4304-8739-3114fa0abd6e.png">

Могу поставить только 12 баллов

2022-11-07 17:32 UTC, konstantinzelinsky commented
Также есть еще ошибка валидатора
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/57330800/200376446-7a71b8df-c634-46dc-8304-7af4860a65d8.png">

2022-11-07 17:54 UTC, konstantinzelinsky approved these changes

2022-11-07 17:54 UTC, merged

2022-11-07 17:55 UTC, konstantinzelinsky commented
Еще обрати внимание на то, что из сообщения в коммите должно быть понятно, что изменено
`Final version` из такого сообщения не понятно.